apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: retrodep-xaie
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: retrodep-xaie
    app.kubernetes.io/part-of: test-app-641
  name: retrodep-xaie
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-retrodep
      app.kubernetes.io/instance: retrodep-xaie
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-retrodep
        app.kubernetes.io/instance: retrodep-xaie
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-641/retrodep-xaie@sha256:fd6fb9fe88840f269e5ed87aaa31fcfb1865c331cfa91bb2166576fe89c80a6e
        name: my-retrodep
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
