apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pip-e2e-test-qjqb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pip-e2e-test-qjqb
    app.kubernetes.io/part-of: test-app-641
  name: pip-e2e-test-qjqb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: pip-e2e-test
      app.kubernetes.io/instance: pip-e2e-test-qjqb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pip-e2e-test
        app.kubernetes.io/instance: pip-e2e-test-qjqb
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-641/pip-e2e-test-qjqb@sha256:78218827cd24ac5e2b5a01f4d6725c5c1335e7fcbf090e3f6216d6415716886c
        name: pip-e2e-test
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
