apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-ev1m
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-ev1m
    app.kubernetes.io/part-of: test-app-641
  name: devfile-sample-python-basic-ev1m
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-ev1m
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-ev1m
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-641/devfile-sample-python-basic-ev1m@sha256:d47446b3dd448c6c1329530c864d3b8734231078b70881dbdb00a6299ff7adff
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
